[package]
name = "chat-server"
version = "0.1.0"
authors = ["Peter Triller <ptriller@soapwars.de>"]
edition = "2018"

[dependencies]
tokio = { version = "0.3", features = [ "full" ] }
bytes = "0.6.0"
tokio-util = { version = "0.5.0", features = [ "codec" ] }
log = "0.4.11"

[dev-dependencies]
hound = "3.4.0"
audiopus = "0.2.0"
sodiumoxide = "0.2.6"
